# Question a.

In [3]:
# Questrion a.
# for diagram (a), the Transition Matrix A is:
a <- matrix(
  c(0, rep(1/3,3),0,0, rep(1/2,2),1,rep(0,3),1/2,0,1/2,0),
  nrow = 4
);a

[,1]      [,2] [,3] [,4]
[1,] 0.0000000 0.0  1    0.5 
[2,] 0.3333333 0.0  0    0.0 
[3,] 0.3333333 0.5  0    0.5 
[4,] 0.3333333 0.5  0    0.0

In [4]:
# for diagram (b), the Transition Matrix A is:
b <- matrix(
  c(0,rep(1/3,3),rep(0,4),1/2,1/2,1,rep(0,5),1/2,1/2,rep(0,6),1),
  nrow = 5
);b

[,1]      [,2] [,3] [,4] [,5]
[1,] 0.0000000 0.0  1    0.0  0   
[2,] 0.3333333 0.0  0    0.5  0   
[3,] 0.3333333 0.0  0    0.5  0   
[4,] 0.3333333 0.5  0    0.0  0   
[5,] 0.0000000 0.5  0    0.0  1

# Question b

In [5]:
# Question b.
# for diagram (a): Google matrix G is: (q=.15)
q <- .15
K <- matrix(c(rep(1,4*4)), nrow = 4);K

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 1    1    1    1   
[3,] 1    1    1    1   
[4,] 1    1    1    1

In [6]:
Ga <- (1-q) * a + q * (1/4 * K);Ga

[,1]      [,2]   [,3]   [,4]  
[1,] 0.0375000 0.0375 0.8875 0.4625
[2,] 0.3208333 0.0375 0.0375 0.0375
[3,] 0.3208333 0.4625 0.0375 0.4625
[4,] 0.3208333 0.4625 0.0375 0.0375

In [7]:
# for diagram (b): Google matrix G is: (q=.15)
K <- matrix(c(rep(1, 5*5)),nrow = 5);K

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [8]:
# Adjustment: replace the column 5 because it's a dangling node
b[,5] <- rep(1/5, 5);b

[,1]      [,2] [,3] [,4] [,5]
[1,] 0.0000000 0.0  1    0.0  0.2 
[2,] 0.3333333 0.0  0    0.5  0.2 
[3,] 0.3333333 0.0  0    0.5  0.2 
[4,] 0.3333333 0.5  0    0.0  0.2 
[5,] 0.0000000 0.5  0    0.0  0.2

In [9]:
Gb <- (1-q) * b + q * (1/5 *K);Gb

[,1]      [,2]  [,3] [,4]  [,5]
[1,] 0.0300000 0.030 0.88 0.030 0.2 
[2,] 0.3133333 0.030 0.03 0.455 0.2 
[3,] 0.3133333 0.030 0.03 0.455 0.2 
[4,] 0.3133333 0.455 0.03 0.030 0.2 
[5,] 0.0300000 0.455 0.03 0.030 0.2

# Question c:
- Diagram (a) doesn't have dangling node.
- Diagram (b) has one dangling node, it's state 5.

In [10]:
# Question c:
# Does either graph have a dangling node? If so which one(s)?
Answer_a <- "Diagram (a) doesn't have dangling node node, while Diagram (b) has one 
dangling node, it's state 5."


# Question d:
- "As far as I can see, neither graph has a disconnected node"

In [11]:
# Question d:
# Does either graph have a disconnected node? 
Answer_b <- "As far as I can see, neither graph has a disconnected node"

# Question e:

In [12]:
# Question e: 
# Compute the PageRank of each page in the set.
# For Diagram (a):
Ga

[,1]      [,2]   [,3]   [,4]  
[1,] 0.0375000 0.0375 0.8875 0.4625
[2,] 0.3208333 0.0375 0.0375 0.0375
[3,] 0.3208333 0.4625 0.0375 0.4625
[4,] 0.3208333 0.4625 0.0375 0.0375

In [13]:
va <- eigen(Ga);va

eigen() decomposition
$values
[1]  1.0000000+0.0000000i -0.3065298+0.3493292i -0.3065298-0.3493292i
[4] -0.2369403+0.0000000i

$vectors
             [,1]                  [,2]                  [,3]          [,4]
[1,] 0.6964831+0i -0.7552157+0.0000000i -0.7552157+0.0000000i  0.5064856+0i
[2,] 0.2682810+0i  0.3036721+0.3460725i  0.3036721-0.3460725i -0.6056557+0i
[3,] 0.5447780+0i  0.0931532-0.2746779i  0.0931532+0.2746779i -0.3815392+0i
[4,] 0.3823004+0i  0.3583904-0.0713946i  0.3583904+0.0713946i  0.4807092+0i


In [14]:
PageRankA <- va$vectors[,1] / sum(va$vectors[,1]); round(PageRankA, digits = 4)

[1] 0.3682+0i 0.1418+0i 0.2880+0i 0.2021+0i

In [15]:
vb <- eigen(Gb);vb

eigen() decomposition
$values
[1]  1.000000e+00 -4.250000e-01 -3.283472e-01  7.334716e-02  3.338381e-16

$vectors
           [,1]       [,2]       [,3]       [,4]          [,5]
[1,] -0.5120362 -0.7223151 -0.7436111  0.2835064 -1.550291e-15
[2,] -0.4611320  0.4213505  0.3463197  0.2029132 -3.429972e-01
[3,] -0.4611320  0.4213505  0.3463197  0.2029132 -1.714986e-01
[4,] -0.4611320  0.1805788  0.3463197  0.2029132 -3.429972e-01
[5,] -0.3160551 -0.3009646 -0.2953481 -0.8922460  8.574929e-01


In [16]:
PageRankB <- vb$vectors[,1] / sum(vb$vectors[,1]); round(PageRankB, digits = 4)

[1] 0.2315 0.2085 0.2085 0.2085 0.1429